### PR TITLE
Delete old data

### PR DESCRIPTION
**Pull request by sreichel**
1st is to hide mass action option if access is deneid in ACL
2nd is to delete old attribute data (compared old and new set attributes)
3rd is to save some needless read queries
4th is change to delete ALL old attribute data (compared all and new set attributes)

Sorry for commit spam ;)

### CODE REVIEW

**Comment by davidfuhr** [comment]
Can you please rebase and squash your commits?

**Comment by sreichel** [comment]
I'll try ...

**Comment by davidfuhr** [comment]
You dont need to close the PR for rebase/squash.

**Comment by sreichel** [comment]
Hi,

hope your are fine with this PR. Please let me know if i should change anything else.

**Comment by davidfuhr** [comment]
Merged with #ac9251d0fd6e00d3196b0322bab6c5492f8aaf98.

Thanks sreichel!

**Pull request closed without merging**
